

DELETE https://crudcrud.com/api/a88e06f0ff8a4d47a23108addd490317/student/66e67cc7fe837603e816c188
Accept: application/json

###
GET https://crudcrud.com/api/a88e06f0ff8a4d47a23108addd490317/student/66e67cc7fe837603e816c188
Accept: application/json

###
POST https://crudcrud.com/api/a88e06f0ff8a4d47a23108addd490317/student
Content-Type: application/json

{
  "name": "Василий Викторов",
  "grade": 2
}

###
# student id = 66e67cc7fe837603e816c188